caja/urls.py
from django.urls import path

from .views import (
    caja,
    historial,
    eliminar_producto,
    actualizar_producto
)

app_name = 'caja'

urlpatterns = [
    path('', caja, name='caja'),
    path('historial/', historial, name="historial"),
    path('actualizar/<int:pk>', actualizar_producto, name='actualizar_producto'),
    path('eliminar/<int:pk>', eliminar_producto, name='eliminar_producto'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    inicio,
    signIn,
    registro,
    salir,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('inicio', inicio, name='inicio'),
    
    path('login/', signIn, name="login"),
    path('registro/', registro, name="registro"),
    path('salir/', salir, name="salir"),
    
    path('', include('caja.urls', namespace='caja')),
]

caja/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=255) 
    precio = models.PositiveIntegerField()
    cantidad = models.PositiveIntegerField(default=1)
    fecha_venta = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-fecha_venta']
    
    def __str__(self):
        return self.nombre
    
    def total_producto(self):
        return f"{self.precio * self.cantidad}"

caja/forms.py
from django import forms

from .models import Producto

class CalendarioForm(forms.Form):
    fecha = forms.DateField(
        widget = forms.SelectDateWidget(
            attrs={'class':'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'},
            years=range(2023, 2034)
        ),
        
        input_formats=['%Y-%m-%d', '%d/%m/%Y'],
    )
    
class ProductoForm(forms.ModelForm):
    nombre = forms.CharField(
        widget=forms.TextInput(
            attrs={'class':'max-w-lg block w-full shadow-sm dark:bg-dark-third dark:focus:ring-dark-second focus:ring-indigo-500 dark:focus:border-dark-second dark:text-dark-txt focus:border-indigo-500 sm:max-w-xs sm:text-sm dark:border-dark-second border-gray-300 rounded-md'}
        ),
        required=True,
    )
    
    precio = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class':'max-w-lg block w-full shadow-sm dark:bg-dark-third dark:focus:ring-dark-second focus:ring-indigo-500 dark:focus:border-dark-second dark:text-dark-txt focus:border-indigo-500 sm:max-w-xs sm:text-sm dark:border-dark-second border-gray-300 rounded-md'},
        ), 
        required=True,
    )
    
    cantidad = forms.CharField(
        widget=forms.NumberInput(
            attrs={'class':'max-w-lg block w-full shadow-sm dark:bg-dark-third dark:focus:ring-dark-second focus:ring-indigo-500 dark:focus:border-dark-second dark:text-dark-txt focus:border-indigo-500 sm:max-w-xs sm:text-sm dark:border-dark-second border-gray-300 rounded-md'}
        ),
        required=True,
    )
    
    class Meta:
        model = Producto
        fields = ["nombre", "precio", "cantidad"]

class ActualizarProductoForm(forms.ModelForm):
    nombre = forms.CharField(widget=forms.TextInput(
        attrs={'class':'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}
        ), required=True)
    
    precio = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class':'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}
        ), 
        required=True,
    )
    
    cantidad = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class':'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'}
        ),
        required=True,
    )
    
    class Meta:
        model = Producto
        fields = ["nombre", "precio", "cantidad"]

caja/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Producto
from .forms import ProductoForm, ActualizarProductoForm, CalendarioForm

# Create your views here.

@login_required
def  caja(request):
    fecha_actual = timezone.now()
    form_crear = ProductoForm(request.POST or None, initial={'cantidad': 1})
    productos = Producto.objects.filter(usuario=request.user, fecha_venta__date=fecha_actual)
    
    venta = 0
    
    for producto in productos:
        venta += producto.precio * producto.cantidad
          
    if request.method == 'POST':
        
        if form_crear.is_valid():
            nuevo_producto = form_crear.save(commit=False)
            nuevo_producto.usuario = request.user
            
            if nuevo_producto.precio < 50 and nuevo_producto.cantidad < 1:
                messages.warning(request, "Error, Los datos precio y cantidad son incorrectos!")
                
            elif nuevo_producto.precio < 50:
                 messages.warning(request, "Error, El precio debe ser mayor a 50!")
                 
            elif nuevo_producto.cantidad < 1:
                 messages.warning(request, "Error, La cantidad debe ser mayor a 1!")
            
            else:
                
                for producto in productos:
                    if nuevo_producto.nombre.replace(" ", "").lower() == producto.nombre.replace(" ", "").lower():
                        messages.info(request, f"El producto {producto.nombre} ya existe")
                        return redirect("caja:actualizar_producto", pk=producto.id)
                
                messages.success(request, f"El producto {nuevo_producto.nombre} ha sido creado!")
                nuevo_producto.save()
                return redirect("caja:caja")
        
        else:
            messages.warning(request, "Los datos son invalidos")

        
    context = {
        "productos" : productos,
        "form_crear" : form_crear,
        "venta" : venta,
        "fecha_actual": fecha_actual,
    }
    
    return render(request, 'pages/caja/caja.html', context)

@login_required
def historial(request):
    fecha = timezone.localtime(timezone.now())
    fecha = fecha.strftime('%Y-%m-%d')
    form_calendario = CalendarioForm(request.POST or None, initial={'fecha': fecha})
    productos = Producto.objects.filter(usuario=request.user, fecha_venta__date=fecha)

    venta = 0
    
    if form_calendario.is_valid():
        fecha = form_calendario.cleaned_data['fecha']
        productos = Producto.objects.filter(usuario=request.user, fecha_venta__date=fecha)
    
    for producto in productos:
        venta += producto.precio * producto.cantidad
        
    context = {
        "productos" : productos,
        "venta" : venta,
        "form_calendario" : form_calendario,
        "fecha" : fecha
    }
    
    return render(request, 'pages/caja/historial.html', context)
    

@login_required
def actualizar_producto(request, pk):
    producto = get_object_or_404(Producto, usuario=request.user, pk=pk)
    form_actualizar = ActualizarProductoForm(request.POST or None, instance=producto)
    
    if request.method == 'POST':
        
        if form_actualizar.is_valid():
            actualizar_producto = form_actualizar.save(commit=False)
            
            if actualizar_producto.precio < 50 and actualizar_producto.cantidad < 1:
                messages.warning(request, "Error, Los datos precio y cantidad son incorrectos!")
                
            elif actualizar_producto.precio < 50:
                 messages.warning(request, "Error, El precio debe ser mayor a 50!")
                 
            elif actualizar_producto.cantidad < 1:
                 messages.warning(request, "Error, La cantidad debe ser mayor a 1!")
                 
            else:
                
                messages.success(request, f"El producto {actualizar_producto.nombre} ha sido actualizado!")
                actualizar_producto.save()
                return redirect("caja:caja")
            
        else:
            messages.warning(request, "Los datos son invalidos!")
    
    contexto = {
        "form_actualizar" : form_actualizar,
        "producto" : producto,
    }

    return render(request, 'pages/caja/actualizar_producto.html', contexto)
  
@login_required  
def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto, usuario=request.user, pk=pk)
    messages.info(request, f"El producto {producto.nombre} ha sido eliminado!")
    producto.delete()
    return redirect("caja:caja")

templates/pages/caja/actualizar_producto.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Actualizar Producto{% endblock title %}

{% block content %}

<div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]" aria-hidden="true">
    <div class="relative left-1/2 -z-10 aspect-[1155/678] w-[36.125rem] max-w-none -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-40rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
  </div>
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Actualizar {{ producto.nombre }}</h2>
    <p class="mt-2 text-lg leading-8 text-gray-600">{{ producto.fecha_venta|date:"SHORT_DATE_FORMAT" }} , {{ producto.fecha_venta|time:"H:i"}}</p>
  </div>


  <form class="mx-auto w-9/12" method="post">
    {% csrf_token %}

        <div class="relative">
            <div class="absolute inset-0 flex items-center" aria-hidden="true">
                <div class="w-full border-t dark:border-dark-second border-gray-300"></div>
            </div>
            <div class="relative flex justify-center my-4">
                <span class="px-2 bg-white dark:bg-dark-second text-sm dark:text-dark-txt text-gray-500">
                Detalles del Producto
                </span>
            </div>
        </div>
      <div class="pb-12">
        <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

            
  
          <div class="sm:col-span-2 sm:col-start-1">
            <label for="id_nombre" class="block text-sm font-medium leading-6 text-gray-900">Nombre</label>
            <div class="mt-2">
              {{ form_actualizar.nombre }}
            </div>
          </div>
  
          <div class="sm:col-span-2">
            <label for="id_cantidad" class="block text-sm font-medium leading-6 text-gray-900">Cantidad</label>
            <div class="mt-2">
              {{ form_actualizar.cantidad}}
            </div>
          </div>
  
          <div class="sm:col-span-2">
            <label for="id_precio" class="block text-sm font-medium leading-6 text-gray-900">Precio</label>
            <div class="mt-2">
              {{ form_actualizar.precio }}
            </div>
          </div>
        </div>
      </div>
  
  
    <div class="mt-2 flex items-center justify-center gap-x-6">
      <a href="{% url 'caja:caja' %}" class="text-sm font-semibold leading-6 text-gray-900">Regresar</a>
      <button type="submit" class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Actualizar</button>
    </div>
  </form>
    
</div>

{% endblock content %}

templates/pages/caja/caja.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

<div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]" aria-hidden="true">
    <div class="relative left-1/2 -z-10 aspect-[1155/678] w-[36.125rem] max-w-none -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-40rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
  </div>
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Total Venta : {{ venta|intcomma }}</h2>
    <p class="my-2 text-lg leading-8 text-gray-600">{{ fecha_actual|date:"SHORT_DATE_FORMAT" }}</p>
    <a href="{% url 'salir' %}" class="py-1 px-2 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-green-700 dark:bg-dark-third bg-green-200 dark:hover:bg-dark-third hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-green-500">Salir</a>
  </div>

<!-- Agregar Producto Vendido -->
<div x-data="{open:false}" class="px-4 mt-2">
    <div class="p-2 border-b border-gray-300 dark:border-dark-third flex">
        <button @click="open=true" class="my-4  mx-auto inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
            <span>
                Agregar Producto Vendido
            </span>
        </button>
        <a href="{% url 'caja:historial' %}" class="my-4  mx-auto inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-yellow-700 dark:bg-dark-third bg-yellow-200 dark:hover:bg-dark-third hover:bg-yellow-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
              Historial
      </a>
    </div>

    <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" @click.away="open = false" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
        <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        
        <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" x-description="Background overlay, show/hide based on modal state." class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" @click="open = false" aria-hidden="true"></div>

        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <div class="inline-block align-bottom dark:bg-dark-second bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">            
            <div>
                <div class="mt-3 text-center sm:mt-5">
                    <h3 class="text-lg leading-6 font-medium dark:text-dark-txt text-gray-900" id="modal-title">
                    Agregar Producto
                    </h3>
                </div>
            </div>


            <form class="form-horizontal dark:text-dark-txt" method="post" >
                {% csrf_token %}

                <!-- This example requires Tailwind CSS v2.0+ -->
                <div class="relative">
                    <div class="absolute inset-0 flex items-center" aria-hidden="true">
                        <div class="w-full border-t dark:border-dark-second border-gray-300"></div>
                    </div>
                    <div class="relative flex justify-center my-4">
                        <span class="px-2 bg-white dark:bg-dark-second text-sm dark:text-dark-txt text-gray-500">
                        Detalles del Producto
                        </span>
                    </div>
                </div>

                <label for="id_nombre" class="block text-sm font-medium dark:text-dark-txt text-gray-700">Nombre</label>
                {{ form_crear.nombre }}

                <label for="id_cantidad" class="mt-2 block text-sm font-medium dark:text-dark-txt text-gray-700">Cantidad</label>
                {{ form_crear.cantidad }}

                <label for="id_precio" class="mt-2 mb-2 block text-sm font-medium dark:text-dark-txt text-gray-700">Precio</label>
                {{ form_crear.precio }}

                <div class="control-group">
                    <div class="controls">
                        <div @click="open=false" class="cursor-pointer mt-4 inline-flex float-left items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
                        Regresar</div>
                        <button type="submit" class="mt-4 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-green-700 dark:bg-dark-third bg-green-200 dark:hover:bg-dark-third hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-green-500">
                        Agregar Producto</button>
                    </div>
                </div>
            </div>
            </form>
        </div>
        </div>
    </div>
</div>
    

<!-- Lista De productos vendidos-->
<div class="w-9/12 m-auto">
    <ul role="list" class="divide-y divide-gray-100">
        {% for producto in productos %}
        <li class="flex justify-between gap-x-6 py-5">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm font-semibold leading-6 text-gray-900">{{ producto.nombre }}</p>
              <p class="text-sm leading-6 text-gray-900 sm:hidden"><strong>Total Vendido:</strong> {{ producto.total_producto|intcomma }}</p>
              <p class="mt-1 truncate text-xs leading-5 text-gray-500 sm:hidden"><strong>Precio Unidad:</strong> {{ producto.precio|intcomma }}</p>
              <p class="mt-1 text-xs leading-5 text-gray-500 sm:hidden"><strong>Cantidad Vendida:</strong> {{ producto.cantidad }}</time></p>
              <p class="mt-1 truncate text-xs leading-5 text-gray-500"><strong>Fecha Venta:</strong> {{ producto.fecha_venta|date:"SHORT_DATE_FORMAT" }} , {{ producto.fecha_venta|time:"H:i" }}</p>
              <a href="{% url 'caja:eliminar_producto' producto.id %}" class="mt-2 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-red-700 dark:bg-dark-third bg-red-100 dark:hover:bg-dark-third hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-red-500">
                Eliminar
              </a>
              <a href="{% url 'caja:actualizar_producto' producto.id %}" class="mt-2 mr-2 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-green-700 dark:bg-dark-third bg-green-100 dark:hover:bg-dark-third hover:bg-green-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:green-red-500">
                Editar
              </a>
            </div>
          </div>
          <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
            <p class="text-sm leading-6 text-gray-900"><strong>Total Vendido:</strong> {{ producto.total_producto|intcomma }}</p>
            <p class="mt-1 truncate text-xs leading-5 text-gray-500 "><strong>Precio Unidad:</strong> {{ producto.precio|intcomma }}</p>
            <p class="mt-1 text-xs leading-5 text-gray-500"><strong>Cantidad Vendida:</strong> {{ producto.cantidad }}</time></p>
          </div>
        </li>
        {% endfor %}
      </ul>
</div>
</div>
{% endblock content %}

templates/pages/caja/historial.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}Historial{% endblock title %}

{% block content %}

<div class="absolute inset-x-0 top-[-10rem] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[-20rem]" aria-hidden="true">
    <div class="relative left-1/2 -z-10 aspect-[1155/678] w-[36.125rem] max-w-none -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%-40rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
</div>
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Total Venta : {{ venta|intcomma }}</h2>
    <p class="my-2 text-lg leading-8 text-gray-600">Fecha : {{ fecha }}</p>
    <a href="{% url 'caja:caja' %}"  class="py-1 px-2 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-green-700 dark:bg-dark-third bg-green-200 dark:hover:bg-dark-third hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-green-500">Regresar</a>
  </div>


<div x-data="{open:false}" class="px-4 mt-2">
  <div class="p-2 border-b border-gray-300 dark:border-dark-third flex">
      <button @click="open=true" class="my-4  mx-auto inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
          <span>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 0 1 2.25-2.25h13.5A2.25 2.25 0 0 1 21 7.5v11.25m-18 0A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75m-18 0v-7.5A2.25 2.25 0 0 1 5.25 9h13.5A2.25 2.25 0 0 1 21 11.25v7.5" />
            </svg>            
          </span>
      </button>
  </div>
<div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" @click.away="open = false" class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
  
  <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" x-description="Background overlay, show/hide based on modal state." class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" @click="open = false" aria-hidden="true"></div>

  <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

  <div class="inline-block align-bottom dark:bg-dark-second bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6">            
      <form class="form-horizontal dark:text-dark-txt" method="post" >
          {% csrf_token %}

          {{ form_calendario.fecha}}

          <div class="control-group">
            <div class="controls">
                <div @click="open=false" class="cursor-pointer mt-4 inline-flex float-left items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-indigo-700 dark:bg-dark-third bg-indigo-100 dark:hover:bg-dark-third hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-indigo-500">
                Regresar</div>
                <button type="submit" class="mt-4 inline-flex float-right items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded dark:text-dark-txt text-green-700 dark:bg-dark-third bg-green-200 dark:hover:bg-dark-third hover:bg-green-300 focus:outline-none focus:ring-2 focus:ring-offset-2 dark:focus:ring-dark-third focus:ring-green-500">
                Cambiar Fecha</button>
            </div>
        </div>
      </form>
  </div>
  </div>
</div>
</div>
    

<!-- Lista De productos vendidos-->
<div class="w-9/12 m-auto">
    <ul role="list" class="divide-y divide-gray-100">
        {% for producto in productos %}
        <li class="flex justify-between gap-x-6 py-5">
          <div class="flex min-w-0 gap-x-4">
            <div class="min-w-0 flex-auto">
              <p class="text-sm font-semibold leading-6 text-gray-900">{{ producto.nombre }}</p>
              <p class="text-sm leading-6 text-gray-900 sm:hidden"><strong>Total Vendido:</strong> {{ producto.total_producto|intcomma }}</p>
              <p class="mt-1 truncate text-xs leading-5 text-gray-500 sm:hidden"><strong>Precio Unidad:</strong> {{ producto.precio|intcomma }}</p>
              <p class="mt-1 text-xs leading-5 text-gray-500 sm:hidden"><strong>Cantidad Vendida:</strong> {{ producto.cantidad }}</time></p>
              <p class="mt-1 truncate text-xs leading-5 text-gray-500"><strong>Fecha Venta:</strong> {{ producto.fecha_venta|date:"SHORT_DATE_FORMAT" }} , {{ producto.fecha_venta|time:"H:i" }}</p>
            </div>
          </div>
          <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
            <p class="text-sm leading-6 text-gray-900"><strong>Total Vendido:</strong> {{ producto.total_producto|intcomma }}</p>
            <p class="mt-1 truncate text-xs leading-5 text-gray-500 "><strong>Precio Unidad:</strong> {{ producto.precio|intcomma }}</p>
            <p class="mt-1 text-xs leading-5 text-gray-500"><strong>Cantidad Vendida:</strong> {{ producto.cantidad }}</time></p>
          </div>
        </li>
        {% endfor %}
      </ul>
</div>
</div>
{% endblock content %}